version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3030:3000"
      - "222:22"

  hydra:
    command:
      serve all --dangerous-force-http --dangerous-allow-insecure-redirect-urls http://gitea.example.com:8000/users/auth/ORY_Hydra/callback
